"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-6(5qz)_rhp#dd4un0ch&jd#e0b1^a$!673w_wb8kh#!=1qjq#!'

DEBUG = True

ALLOWED_HOSTS = ["*", "localhost", "127.0.0.1"]


# ================================================================
#  INSTALLED APPS
# ================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',     # ⭐ REQUIRED FOR FRONTEND

    # Local apps
    'accounts',
    'vendor',
     'catalog',
]


# ================================================================
#  MIDDLEWARE
# ================================================================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",    # ⭐ MUST BE FIRST
    "django.middleware.common.CommonMiddleware",

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ================================================================
#  CORS SETTINGS (⭐ FIX YOUR CORS ERROR)
# ================================================================
CORS_ALLOW_ALL_ORIGINS = True  # DEV MODE ONLY

# Or use this for stricter config:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "accept",
]

# ================================================================
#  URL CONFIG
# ================================================================
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'core.wsgi.application'


# ================================================================
#  DATABASE (PostgreSQL)
# ================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'keelean',
        'USER': 'keelean_user',
        'PASSWORD': 'keelean123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# ================================================================
#  PASSWORD VALIDATION
# ================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ================================================================
#  STATIC & MEDIA FILES
# ================================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ================================================================
#  DRF CONFIG
# ================================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "vendor.authentication.VendorJWTAuthentication",      # ✅ Vendor auth
        "accounts.authentication.AdminVendorJWTAuthentication",  # ✅ Admin auth
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # ✅ Fallback
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer" if DEBUG else "rest_framework.renderers.JSONRenderer",
    ],
}


# ================================================================
#  JWT SETTINGS
# ================================================================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


AUTH_USER_MODEL = 'vendor.Vendor'

# ================================================================
#  WHATSAPP SETTINGS
# ================================================================
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID")
WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN")
WHATSAPP_TEMPLATE = os.getenv("WHATSAPP_TEMPLATE")
