# Generated by Django 6.0.4 on 2026-04-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Add-On',
                'verbose_name_plural': 'Add-Ons',
                'db_table': 'addons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomisationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customisation Option',
                'verbose_name_plural': 'Customisation Options',
                'db_table': 'customisation_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hours_sla', models.IntegerField(help_text='Turnaround hours (48, 24, 4, 2)')),
                ('surcharge_type', models.CharField(choices=[('pct', 'Percentage'), ('fixed', 'Fixed Amount')], default='pct', max_length=20)),
                ('default_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Default surcharge value', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Tier',
                'verbose_name_plural': 'Delivery Tiers',
                'db_table': 'delivery_tiers',
                'ordering': ['hours_sla'],
            },
        ),
        migrations.CreateModel(
            name='FoldingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Folding Option',
                'verbose_name_plural': 'Folding Options',
                'db_table': 'folding_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Item-Category Link',
                'verbose_name_plural': 'Item-Category Links',
                'db_table': 'item_categories',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='items', through='catalog.ItemCategory', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'db_table': 'item_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.itemtype')),
            ],
            options={
                'verbose_name': 'Item-Subcategory Link',
                'verbose_name_plural': 'Item-Subcategory Links',
                'db_table': 'item_subcategories',
            },
        ),
        migrations.CreateModel(
            name='ItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.itemtype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'Item-Service Link',
                'verbose_name_plural': 'Item-Service Links',
                'db_table': 'item_services',
                'unique_together': {('item', 'service')},
            },
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.itemtype'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='services',
            field=models.ManyToManyField(related_name='items', through='catalog.ItemService', to='catalog.servicecategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='services',
            field=models.ManyToManyField(help_text='Which services are available for this category', related_name='categories', to='catalog.servicecategory'),
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_label', models.CharField(help_text='Label shown in UI', max_length=120)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('boolean', 'Boolean'), ('number', 'Number')], default='select', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_items', models.ManyToManyField(blank=True, related_name='attribute_types', to='catalog.itemtype')),
                ('applicable_services', models.ManyToManyField(blank=True, related_name='attribute_types', to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'Attribute Type',
                'verbose_name_plural': 'Attribute Types',
                'db_table': 'attribute_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
                ('services', models.ManyToManyField(help_text='Which services are available for this subcategory', related_name='subcategories', to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'db_table': 'subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='itemtype',
            name='subcategories',
            field=models.ManyToManyField(related_name='items', through='catalog.ItemSubcategory', to='catalog.subcategory'),
        ),
        migrations.AddField(
            model_name='itemsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subcategory'),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surcharge_pct', models.DecimalField(decimal_places=2, default=0, help_text='Optional % surcharge (e.g., Silk = +10%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attributetype')),
            ],
            options={
                'verbose_name': 'Attribute Option',
                'verbose_name_plural': 'Attribute Options',
                'db_table': 'attribute_options',
                'ordering': ['attribute_type__name', 'name'],
                'unique_together': {('attribute_type', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('item', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='itemsubcategory',
            unique_together={('item', 'subcategory')},
        ),
    ]
