# Generated by Django 5.2.8 on 2026-04-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomisationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoldingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_addons', to='catalog.addon')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.itemtype')),
            ],
            options={
                'unique_together': {('item_type', 'addon')},
            },
        ),
        migrations.CreateModel(
            name='ItemCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customisation_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_customisations', to='catalog.customisationoption')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customisation_options', to='catalog.itemtype')),
            ],
            options={
                'unique_together': {('item_type', 'customisation_option')},
            },
        ),
        migrations.CreateModel(
            name='ItemFolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folding_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_foldings', to='catalog.foldingoption')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folding_options', to='catalog.itemtype')),
            ],
            options={
                'unique_together': {('item_type', 'folding_option')},
            },
        ),
    ]
